### ISSUE TITLE
On watch, every single file calls out to Git

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/jekyll-last-modified-at#24]
Pre-0.3.0, Jekyll sites would crash with this plugin and `--watch`. Now, they remain, but generation takes a really long time, because every single file needs a Git call to check the time.

@parkr Is there a way to run a plugin _once_, before the server starts up, and not every time an auto-regeneration occurs? If not, the only thing I can think of is to preserve some kind of hash, like `@matches[absolute_path_to_article] = last_change`, and just not even attempt the last_modified_at check if the file was checked once before.

**Comment by AnandLA** [comment]
How do I install this as a plugin within jekyll ... I created a _plugin directory and git cloned into it now what ?

**Comment by 888ba8** [comment]
@AnandLA @parkr @gjtorikian I can only use 

`{% last_modified_at %}`

If I try to include `{% page.last_modified_at %}` in my layout, I get the following error, when I try to `bundle exec jekyll build`:
`
Liquid syntax error (line 1): Unknown tag 'page' in /_layouts/page.html`

How to fix this please?

**Comment by mraible** [comment]
I'm experiencing a similar issue to @888ba8. 

```
Liquid Exception: No such file or directory - /Users/mraible/dev/path/to/blog/tags/android/index.html does not exist! in /_layouts/tag.html
jekyll 3.9.0 | Error:  No such file or directory - /Users/mraible/dev/path/to/blog/_source/blog/tags/android/index.html does not exist!
```

If I remove `{{ page.last_modified_at }}` and replace it with `{% last_modified_at %}`, I get the same error.

Anyone figure out a way to add "Last updated" to a Jekyll blog? I tried a few other solutions, but none seem to work.
