### ISSUE TITLE
Compatible with GitHub Page

### ISSUE THREAD

**Issue by yi-tang** [gjtorikian/jekyll-last-modified-at#32]
Hi,

I wonder if this plugin works with GitHub Page?  

Also, could you please add a installation section on README.MD for Jekyll newbie? 

Many thanks
Yi

**Comment by jhabdas** [comment]
I started using this gem yesterday and can confirm, at least for collections, it pulls the timestamp from the individual asset. @gjtorikian Please let me know if you'd like to see an example implementation. /cc @parkr @pathacks
