### ISSUE TITLE
Unix time for static files (rather than Git time)

### ISSUE THREAD

**Issue by pathawks** [gjtorikian/jekyll-last-modified-at#33]
It seems that, for pages and posts, the modified time is when they were committed to the Git repo.

Unless I am misunderstanding somethinh, it seems that for static files the modified time is what the file system has stored rather than when it was committed to the repo. Is there a reason for this?

Have *I* done something wrong? (Quite likely)

**Comment by gjtorikian** [comment]
The modified time should be used [if and only if](https://github.com/gjtorikian/jekyll-last-modified-at/blob/0eaeb28378945d789faf15363e618429788695e1/lib/jekyll-last-modified-at/determinator.rb#L28-L41) information cannot be ascertained from the Git repo on when it was committed. Are you using the plugin in a Git repo?

**Comment by pathawks** [comment]
> Are you using the plugin in a Git repo?

Yup.

Here is what I am looking at: https://travis-ci.org/jekyll/jekyll-sitemap/jobs/47481786

`http://example.org/jekyll-last-modified-at/static-file.html` was created in the same commit as `http://example.org/2015/01/18/jekyll-last-modified-at.html` and `http://example.org/jekyll-last-modified-at/page.html`, but the latter two display the date they were committed while the former displays the file system modified date (which will always be different on Travis).

**Comment by gjtorikian** [comment]
It looks like *jekyll-last-modified-at/static-file.html* [does not have frontmatter](https://github.com/jekyll/jekyll-sitemap/pull/35/files#diff-7) associated with it, whereas the other two do. I wonder if that would affect things here. /cc @parkr Any thoughts here?

**Comment by pathawks** [comment]
Right; it is a static file, rather than a page. Jekyll treats them differently.

**Comment by parkr** [comment]
Static files unfortunately do not have any of these same attributes. It would make sense to add a `data` Hash which is then used in `to_liquid`, but at the moment, that has not been implemented. :(

**Comment by pathawks** [comment]
My mistake, **jekyll-last-modified-at** ignores static files completely; it does not get the file system modified time.

It seems that this is the expected behavior, barring #34 

Mea culpa.
