### ISSUE TITLE
Deprecate {% last_modified_at %}

### ISSUE THREAD

**Issue by benbalter** [gjtorikian/jekyll-last-modified-at#36]
In the readme it says:

> (It's generally more performant to use the page.last_modified_at version of this plugin.)

Reading through things, it looks like `page.last_modified_at` is calculate as page meta across all documents, whatever you do.

Why have two ways to do the same thing? Why not (at the next major version), only support the meta version? That way you have half the invocations to maintain, and users are always use the more performant method.

**Comment by gjtorikian** [comment]
👍
