### ISSUE TITLE
Deprecation warning in Jekyll 3.0.0

### ISSUE THREAD

**Issue by Ipstenu** [gjtorikian/jekyll-last-modified-at#37]
Deprecation: Collection#each should be called on the #docs array directly.

Called by /usr/local/lib/ruby/gems/2.2.0/gems/jekyll-last-modified-at-0.3.4/lib/jekyll-last-modified-at/generator.rb:7:in `block in generate'.

**Comment by tjkohli** [comment]
Bump?

**Comment by bendobos** [comment]
Any news on this?

**Comment by nephen** [comment]
problem: Deprecation: Collection#each should be called on the #docs array directly.

**Comment by dshevtsov** [comment]
same issue in jekyll 3.0.5 when I use `{{ page.last_modified_at }}` (jekyll-last-modified-at (0.3.4))
