### ISSUE TITLE
Is this gem still compatible with the latest releases of Jekyll?

### ISSUE THREAD

**Issue by fusion809** [gjtorikian/jekyll-last-modified-at#39]
Hi,

I have attempted to include this gem on my [Jekyll site](https://fusion809.github.io) ([source](https://github.com/fusion809/fusion809.github.io)) by adding `<time datetime="{{ page.last_modified_at | date:"%r, %A %d %B %Y" }}" itemprop="dateModified"><br/><b>Last modified</b>: {{ page.last_modified_at | date:"%I:%M %p %A, %d %B %Y" }}</time>` to my [_layouts/post.html](https://github.com/fusion809/fusion809.github.io/blob/master/_layouts/post.html) file and I included the jekyll-last-modified-at gem in my `_config.yml` file as shown in the README of this repo and even though it is included in http://fusion809.github.io/2016/01/07/comparison-of-free-operating-systems/ as you can see the last modified field is left blank. The only way it gets a value is I assign it manually in the front matter of the post. Correct me if I am wrong but isn't this plugin meant to get the last modified date from Git? 

Thanks for your time,
Brenton

**Comment by gjtorikian** [comment]
Nope, but @parkr started a PR: https://github.com/gjtorikian/jekyll-last-modified-at/pull/38
