### ISSUE TITLE
Deprecation warning for posts in Jekyll 3.1.3

### ISSUE THREAD

**Issue by iloveip** [gjtorikian/jekyll-last-modified-at#41]
Hi there,

After I installed this plugin, I get the following deprecation warning:

```
Deprecation: posts.each should be changed to posts.docs.each.
                    Called by /Users/svetlana/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/jekyll-last-modified-at-0.3.4/lib/jekyll-last-modified-at/generator.rb:7:in `block in generate'.
```

I don't know if it's the same thing, as in issue #37 that has already been reported.

**Comment by jp26jp** [comment]
+1

**Comment by ilg-ul** [comment]
+1

any chance to fix this problem?

**Comment by SummerBuger** [comment]
+1 
who can help me with this problem???

**Comment by michaelx** [comment]
@SummerBuger feel free to check out my lightweight [alternative](https://github.com/michaelx/jekyll-last-modified). Using it in production since half a year.

**Comment by aav7fl** [comment]
PR #43 fixed this for me. 

Explanation: My issue was that [Jekyll-sitemap](https://github.com/jekyll/jekyll-sitemap) was requiring Jekyll 3.3 and was depending on jekyll-last-modified-at 0.3.4 (which made the deprecated call) and not 1.0.0 (which fixed that I think). In order for Jekyll-sitemap to use 1.0.0 (or in this case, 1.0.1), some dependencies needed to be updated.

I just ran `gem update` after these latest commits and everything is working great again. No more warning.

**Comment by gjtorikian** [comment]
Gem is locked to `>= 3.7`, and GitHub Pages itself runs 3.8. Seems like a fix for this was made anyhow, closing as stale.
