### ISSUE TITLE
Are there any plans for version 1.0.0 to accept running with Jekyll 3.3?

### ISSUE THREAD

**Issue by carlosdelfino** [gjtorikian/jekyll-last-modified-at#44]
Hello.

Are there any plans for version 1.0.0 to accept running with Jekyll 3.3?

**Comment by ilg-ul** [comment]
probably a duplicate of #41

**Comment by gjtorikian** [comment]
Nope, sorry, 3.7 is going to be the minimum, GitHub Pages itself runs 3.8.
