### ISSUE TITLE
jekyll 3.2.1 | Error:  Liquid syntax error (line 56): Unknown tag 'last_modified_at'

### ISSUE THREAD

**Issue by juanpabloaj** [gjtorikian/jekyll-last-modified-at#45]
When I run 

    jekyll serve

I get this message

    jekyll 3.2.1 | Error:  Liquid syntax error (line 56): Unknown tag 'last_modified_at'

I installed `jekyll-last-modified-at` with 

    gem install jekyll-last-modified-at

**Comment by zx1986** [comment]
Did you try add `gem 'jekyll-last-modified-at'` to a Gemfile in the same directory, then `bundle` ?

```
bundle install
bundle exec jekyll server
```

**Comment by Messjer** [comment]
I put `group: :jekyll_plugins` in `Gemfile` and it works for me.
```
#Gemfile
gem "jekyll-last-modified-at", group: :jekyll_plugins
```

**Comment by gjtorikian** [comment]
README has been updated with this info, sorry for the trouble.
