### ISSUE TITLE
I'm looking for maintainers/sponsors

### ISSUE THREAD

**Issue by gjtorikian** [gjtorikian/jekyll-last-modified-at#79]
People not only use this project, but depend on it. After building open source software for over a decade, I'm always surprised when that happens.

Unfortunately, I don't really use Jekyll as often as I used to, and I don't really have a need for this plugin. There are quite a few open issues representing thorny problems; I'm (passively) looking for contributors to help maintain the repo.

Alternatively, a GitHub Sponsorship would be nice to show your appreciation and will motivate me to work on this (and other plugins) more. Stars can't pay the rent I'm afraid.

**Comment by xplosionmind** [comment]
Thanks a lot for your work! I’m one of those who actually “**depend**” on the plugin, thus an active development may be more than welcomed. Thanks again, best wishes!

**Comment by johnpitchko** [comment]
Hi there, just found this plugin. I ran into a few bugs which I would like to help fix. I've worked on a few plugins before so I know the basics.

**Comment by gjtorikian** [comment]
PRs are always accepted.
