### ISSUE TITLE
Gemspec version differs from GitHub release version

### ISSUE THREAD

**Issue by michaelnordmeyer** [gjtorikian/jekyll-last-modified-at#96]
The current version of this plugin is 1.3.0, which is declaed in `version.rb` and used in the `.gemspec` file.

But the last release version on GitHub is 1.1.0.

This gave me some trouble, because I only looked at the GitHub release version when adding this gem to my Gemfile with a pessimistic version operator, and Jekyll's build failed.

Could you please release a new version on GitHub?

**Comment by gjtorikian** [comment]
this has been fixed!
